version: "3"

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    user: root
    volumes:
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend

  backend:
    restart: unless-stopped
    container_name: backend
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend/:/backend/
      # - static_volume:/backend/static # <-- bind the static volume
    # stdin_open: true
    tty: true
    # networks:
    #   - backend_network
    expose:
      - 8080
    # env_file:
    #   - ./backend/.env
    command: gunicorn --bind :8080 backend.wsgi:application

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["yarn", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/frontend/
      - build_folder:/frontend/build
      - ./frontend/node_modules/:/frontend/node_modules
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:8000
    tty: true

volumes:
  build_folder:
  static_volume:
  prometheus_data: {}
  grafana_data: {}
